### ISSUE TITLE
ASTInterpreter docs

### ISSUE THREAD

**Issue by ViralBShah** [Keno/Gallium.jl#65]
The ASTInterpreter docs are essential to using Gallium. Since most users will be installing Gallium directly, I am guessing this repo is where they will look for instructions.

The simplest thing would be to link the ASTInterpreter docs here. I am also guessing that some of this should start getting linked into the Julia manual.

Cc @StefanKarpinski

**Comment by StefanKarpinski** [comment]
@Keno, @JeffBezanson and I had discussed the possibility of moving packages like `ASTInterpreter` into the `Gallium` package instead of having it remain outside.

**Comment by ViralBShah** [comment]
That may be even better.

**Comment by StefanKarpinski** [comment]
There's also a possibility that the AST interpreter could become *the* Julia interpreter and thus move into Base. There are a number of reasons we might want an interpreter, especially to reduce compilation time.

**Comment by Keno** [comment]
Jeff and I decided against merging ASTInterpreter into Gallium because Gallium pulls in quite a number of extra dependencies. To the other point, we already have an interpreter in Base, which is significantly faster than ASTInterpreter. ASTInterpreter was designed for interactivity, not speed of execution, and most of the ASTInterpreter code base is dedicated to this functionality (the actual interpreting itself takes ~100 lines or so). I'll make the mention of ASTInterpreter in the docs a link.

**Comment by StefanKarpinski** [comment]
I'm not entirely thrilled about where we're headed with this: multiple parsers, multiple interpreters... I realize these all exist for pragmatic and currently necessary reasons, but it seems like it would be good for unification to be a long term goal.

**Comment by Keno** [comment]
JuliaParser is designed as a replacement for the base parser, and is a significant amount of code. The interpreter is not and is only about ~100 lines.

**Comment by tkelman** [comment]
There might also be other non debugging tooling use cases for the individual pieces here.

**Comment by ViralBShah** [comment]
Where should users find the debugger documentation? It seems silly to ask them to look in two places, even if linked.

**Comment by tkelman** [comment]
Sure, debugger docs may as well be in one place even if all the code isn't.

**Comment by ViralBShah** [comment]
These are now linked from the README, even if not in one place yet.
